### ISSUE TITLE
请教一个kafka消费的问题

### ISSUE THREAD

**Issue by solarhell** [137-rick/http-kafka-gateway#1]
您好，我也在做类似的http消费kafka的服务。
请问为什么要把消息先落到本地文件呢？

另外还有一个问题，如果是http形式，可能后端有多台机器同时消费kafka，如何保证请求落到不同机器的情况下，也能对一个topic完全消费呢？因为不同机器订阅不同的分区，有的分区可能没有消息了。

**Comment by lazycathome** [comment]
> 您好，我也在做类似的http消费kafka的服务。
> 请问为什么要把消息先落到本地文件呢？
> 
> 另外还有一个问题，如果是http形式，可能后端有多台机器同时消费kafka，如何保证请求落到不同机器的情况下，也能对一个topic完全消费呢？因为不同机器订阅不同的分区，有的分区可能没有消息了。

您这个需求，最好是落到Redis集群、Memcache中；

**Comment by milksteven** [comment]
@solarhell @lazycathome 可以讨论一下？落地到Redis集群和Memcache，是指将消息先poll到第三方存储中？这样这个http代理如果是多实例的话就能共享消息数据了，但是这样的问题是消息就有两份了。其实在每个Proxy上开一个Consumer来进行消费是可以的，因为在HTTP请求流量轮询的情况下，总会消费到消息的，唯一有问题的，是消费和ACK请求必须在同一个Proxy实例上，不然就有问题了，这种情况就变得客户端使用HTTP请求消费数据就会变得有状态了，需要客户端维护这套关系。

**Comment by 137-rick** [comment]
请求内处理完毕就行了～

**Comment by milksteven** [comment]
> 请求内处理完毕就行了～

不太理解什么意思，能具体讲解下？
目前我看到的官方的kafka-rest，都需要绑定在一个proxy上进行消费。

**Comment by 137-rick** [comment]
> > 请求内处理完毕就行了～
> 
> 不太理解什么意思，能具体讲解下？ 目前我看到的官方的kafka-rest，都需要绑定在一个proxy上进行消费。

首先，放到redis只是为了防止被写的服务因为被kill而丢失推送数据，所以核心用它做了信息合并，每个proxy将信息放到一个特定的list内即可，不过这个方式其实只是比较粗暴的方式，现代是不提倡这样做的。消费这是proxy消费了kafka的消息后，发送http请求给我们的业务接口，如果我们业务接口返回200处理完成就会ack，同时消费服务是按分区进行消费的，所以多个proxy如果是同一个group是不会消费到相同的数据的
